[project]
name = "CSCI5550-FileSystem-Project"
version = "0.1.0"
requires-python = ">=3.14.2"
dependencies = ["pytest>=9.0.1"]

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-rAx"
testpaths = "tests"
log_cli = true
log_cli_level = "INFO"